Fixed the upstream bug in the init script where failure to run scanswitch would cause it to try and load 127.script.
FossilOrigin-Name: 667edea287a7060f3f9b2169308a6fbcee66cd26

diff --git a/etc/pidp8i-init.in b/etc/pidp8i-init.in
--- a/etc/pidp8i-init.in
+++ b/etc/pidp8i-init.in
@@ -42,13 +42,15 @@ do_start() {
 
 	$scanswitch >/dev/null 2>&1
 	script=$?
-	# FIXME: -gt 8 case not handled!  Can be 127 for no bin.
-	if [ $script -ne 8 ]; then
+	if [ $script -eq 8 ]; then
+	    echo "PiDP-8/I STOP switch detected, aborting." >&2
+	    exit 0
+	elif [ $script -lt 8 ]; then
 	    pidpscript="$prefix/bootscripts/""$script"".script"
 	    echo "$pidpscript"
 	else
-	    echo "PiDP-8/I STOP switch detected, aborting." >&2
-	    exit 0
+		echo "Bad return value $script from $scanswitch!"
+		exit 1
 	fi
 
 	log_daemon_msg "Starting PiDP-8/I" "pidp"
