The bosi process was doing the "rename pi to pidp8i" step after the software configure and build step, so that the user name "pi" was configured into the shipping init script and such.  Split the usermod steps into two stages, rename user and set password, which now surrounds a new "build" step between "init" and "prepare".  The latter is what remains of the old "reset" step.
FossilOrigin-Name: 2866116923645d1d31acd5141f9c354f602775a4

diff --git a/tools/bosi b/tools/bosi
--- a/tools/bosi
+++ b/tools/bosi
@@ -33,7 +33,7 @@ function usage() {
 	cat <<USAGE
 usage: $0 <verb> [tag]
 
-    The available verbs are init, reset, shrink, image, and finish.
+    The available verbs are init, build, prepare, shrink, image, and finish.
 
     You may include a tag parameter with the 'image' and 'finish' verbs
     to override the default tag ('ils') used in image and zip file
@@ -65,13 +65,38 @@ topdir="$($greadlink -f "$(dirname "$this")"/..)"
 
 # Initial steps
 function do_init() {
-	sudo apt-get update && sudo apt-get -y upgrade || true
+	if [ "$USER" != "root" ]
+	then
+		echo "The init step has to be run as root.  The explanation is"
+		echo "given in the section for 'init' in RELEASE-PROCESS.md."
+		echo
+		exit 1
+	fi
 
-	test "$USER" = "root" && exec sudo -i -u $nu $nh/bosi init
-	cd $HOME
+	apt-get update && apt-get -y upgrade || true
 
-	test -n "$(type -p fossil)" || sudo apt-get -y install fossil
-	test -f /usr/include/curses.h || sudo apt-get -y install libncurses-dev
+	test -n "$(type -p fossil)" || apt-get -y install fossil
+	test -f /usr/include/curses.h || apt-get -y install libncurses-dev
+
+	if [ ! -e "$nh" ]
+	then
+		# First pass on a clean SD card: rename 'pi' user to 'pidp8i'
+		# and move its home directory.  Must shut simulator down first
+        # else user "pi" will still be in use.
+        systemctl stop pidp8i
+		usermod -d $nh -l $nu -p $encpass -m pi 
+	fi
+}
+
+
+# Clone repo and build the software under [new] pidp8i account
+function do_build() {
+	if [ "$USER" != "$nu" ]
+	then
+		echo "The build step has to be run as $nu."
+		echo
+		exit 1
+	fi
 
 	if [ ! -d museum ]
 	then
@@ -91,43 +116,30 @@ function do_init() {
 	fi
 
 	tools/mmake
-	sudo make install || true
+	sudo make install || true       # don't care about return code
 	sudo reboot
 }
 
 
-# This script resets the OS's configuration to a clean first boot state.
-function do_reset() {
-	if [ "$USER" != "root" ]
+# This script prepares the OS's configuration to a clean first boot state.
+function do_prepare() {
+	if [ "$USER" != "$nu" ]
 	then
-		echo "The reset step has to be run as root.  The explanation is"
-		echo "given in the section for 'reset' in RELEASE-PROCESS.md."
+		echo "The prepare step has to be run as $nu."
 		echo
 		exit 1
 	fi
 
 	history -c ; rm -f ~/.bash_history
-	test "$USER" = "root" || exec sudo $this reset
 
-	shred -u /etc/ssh/*key* || true             # allow multiple resets
-	dphys-swapfile uninstall || true
-	dd if=/dev/zero of=/junk bs=1M || true		# it *will* error-out!
-	rm -f /junk
+	sudo shred -u /etc/ssh/*key* || true         # allow multiple passes
+	sudo dphys-swapfile uninstall || true
+	sudo dd if=/dev/zero of=/junk bs=1M || true  # it *will* error-out!
+	sudo rm -f /junk
 	encpass=$(openssl passwd -1 edsonDeCastro1968)
-	if [ -e "$nh" ]
-	then
-		# A prior pass already renamed the default user and moved its
-		# home directory, so just change the password.
-		usermod -p $encpass pidp8i
-	else
-		# First pass on a clean SD card: rename 'pi' user to 'pidp8i'
-		# and move its home directory.  Must shut simulator down first
-        # else user "pi" will still be in use.
-        systemctl stop pidp8i
-		usermod -d $nh -l $nu -p $encpass -m pi 
-	fi
-	passwd -e pidp8i
-	poweroff
+    sudo usermod -p $encpass pidp8i
+	sudo passwd -e pidp8i
+	sudo poweroff
 }
 
 
@@ -261,7 +273,8 @@ function do_finish() {
 set -e
 case "$verb" in
 	in*) do_init ;;
-	re*) do_reset ;;
+	bu*) do_build ;;
+	pr*) do_prepare ;;
 	sh*) do_shrink ;;
 	im*) do_image ;;
 	fi*) do_finish ;;
